### ISSUE TITLE
Single line plot?

### ISSUE THREAD

**Issue by cojarbi** [SonarSonic/DrawingBotV3#112]
Is there a specific setting that ill allow to plot/trace a single line either from a actual trace or from an svg.

Thanks in advance

**Comment by SonarSonic** [comment]
There are a few PFMs which are designed to create create single line plots from images. If they have the following in their name "TSP", "Circular Scribbles", "Hatch", "Spiral" they do this by default. It is also possible to make "Sketch" PFMs create single line plots by changing "Should Lift Pen" to false.

For SVGs you can import them and then switch to another PFM instead of SVG Converter and the SVG will be treated like an image, so then you can use the styles mentioned above.

**Comment by cojarbi** [comment]
Ill give that a try, thanks
