### ISSUE TITLE
MacOS Issues: "Damaged and can't be opened" - Solution

### ISSUE THREAD

**Issue by SonarSonic** [SonarSonic/DrawingBotV3#77]

**Comment by JackWH** [comment]
This issue seems to be resolved. Ventura apparently changed the warning dialog which appears when opening an unsigned application, and added a second layer of confirmation too.

The app can be opened by going to System Preferences --> Privacy and Security, then clicking "Open Anyway". The OS will give a second error, but returning to System Preferences and following the same process again will force it to open.

**Comment by SonarSonic** [comment]
Thanks @JackWH - another fix for people with this issue is allowing apps from more sources.

![image](https://user-images.githubusercontent.com/10425594/206433335-8268ad04-83ce-4d84-a284-09360cc43a4d.png)

**Comment by SonarSonic** [comment]
Fixed in v1.5.2
